kind: Job
apiVersion: batch/v1
metadata:
  name: apim-demo-setup-job
  namespace: tools
  labels:
    job-name: apim-demo-setup-job
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  selector: {}
  template:
    metadata:
      name: run
      labels:
        job-name: apim-demo-setup-job
    spec:
      containers:
        - name: run
          image: 'quay.io/vbudi/apic-job:1.0'
          command:
            - "./apic-initial-config.sh"
            - "&&"
            - "./apic-new-porg.sh"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: apic-setup-mail
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler