apiVersion: apps/v1
kind: Deployment
metadata:
  name: apic-publish-deployment
  namespace: tools
spec:
  selector:
    matchLabels:
      app: apicjob
  replicas: 3
  template:
    metadata:
      labels:
        app: apicjob
    spec:
      containers:
        - name: run
          image: 'quay.io/vbudi/apic-job:1.1'
          command:
            - "/user1/waiting.sh"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always